## Fixed-Type Arrays in Python

Python offers several different options for storing data in efficient, fixed-type data buffers. The built-in array module (available since Python 3.3) can be used to create dense arrays of a uniform type:

In [ ]:
import numpy as np
import array as arr

L = np.array(range(1, 10))

A = arr.array('i', L) # Here 'i' is a type code indicating the contents are integers.
print (A)

# NumPy arrays can explicitly be multidimensional; here’s one way of initializing a multidimensional array
# nested lists result in multidimensional arrays
np.array([range(i,i+3) for i in (2,4,6)])



array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy. Here are several examples:

In [9]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)


array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [13]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)

np.arange(0, 20, 2)

# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))


array([[0.8618796 , 0.69079353, 0.57480433],
       [0.46290401, 0.8256618 , 0.55494367],
       [0.69157264, 0.4111524 , 0.32543866]])

In [19]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1

np.random.normal(0,1,(3,3))

array([[-1.46604827,  0.79907927,  0.46915602],
       [-0.7102526 , -1.16602262, -0.81090017],
       [-0.37697882,  1.81241394,  0.66540366]])

In [22]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0,10,(3,3))

array([[5, 6, 1],
       [2, 4, 1],
       [8, 8, 3]])

In [25]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
# before using this array, you should always fill it with your own values, either with array indexing or with the fill() method

np.empty(3)

array([1., 1., 1.])

## NumPy Standard Data Types

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations. Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

<img src="../images/numpy%20data%20type.png" width="600" alt="numpy data type">
