## Fixed-Type Arrays in Python

Python offers several different options for storing data in efficient, fixed-type data buffers. The built-in array module (available since Python 3.3) can be used to create dense arrays of a uniform type:

In [ ]:
import numpy as np
import array as arr

L = np.array(range(1, 10))

A = arr.array('i', L) # Here 'i' is a type code indicating the contents are integers.
print (A)

# NumPy arrays can explicitly be multidimensional; here’s one way of initializing a multidimensional array
# nested lists result in multidimensional arrays
np.array([range(i,i+3) for i in (2,4,6)])



array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy. Here are several examples:

In [9]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)


array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [13]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)

np.arange(0, 20, 2)

# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))


array([[0.8618796 , 0.69079353, 0.57480433],
       [0.46290401, 0.8256618 , 0.55494367],
       [0.69157264, 0.4111524 , 0.32543866]])

In [19]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1

np.random.normal(0,1,(3,3))

array([[-1.46604827,  0.79907927,  0.46915602],
       [-0.7102526 , -1.16602262, -0.81090017],
       [-0.37697882,  1.81241394,  0.66540366]])

In [22]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0,10,(3,3))

array([[5, 6, 1],
       [2, 4, 1],
       [8, 8, 3]])

In [25]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
# before using this array, you should always fill it with your own values, either with array indexing or with the fill() method

np.empty(3)

array([1., 1., 1.])

## NumPy Standard Data Types

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations. Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

<img src="../images/numpy%20data%20type.png" width="600" alt="numpy data type">


## The Basics of NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation:
even newer tools like Pandas are built around the NumPy array. This sec‐tion will present several examples using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays. While the types of operations shown here may seem a bit dry and pedantic

We’ll cover a few categories of basic array manipulations here:

- Attributes of arrays
Determining the size, shape, memory consumption, and data types of arrays

- Indexing of arrays
Getting and setting the value of individual array elements

- Slicing of arrays
Getting and setting smaller subarrays within a larger array

- Reshaping of arrays
Changing the shape of a given array

- Joining and splitting of arrays
Combining multiple arrays into one, and splitting one array into many

### NumPy Array Attributes

First let’s discuss some useful array attributes. We’ll start by defining three random arrays: a one-dimensional, two-dimensional, and three-dimensional array. We’ll use NumPy’s random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run


In [35]:
np.random.seed(42) # Set the random seed to 42 for reproducibility

x1 = np.random.randint(10, size=6) # One-dimensional array of 6 random integers in the range 0-9
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array of shape (3, 4, 5) with random integers in the range 0-9

print(x1)
print(20*'-')

print(x2)
print(20*'-')

print(x3)
print(20*'-')

[6 3 7 4 6 9]
--------------------
[[2 6 7 4]
 [3 7 7 2]
 [5 4 1 7]]
--------------------
[[[5 1 4 0 9]
  [5 8 0 9 2]
  [6 3 8 2 4]
  [2 6 4 8 6]]

 [[1 3 8 1 9]
  [8 9 4 1 3]
  [6 7 2 0 3]
  [1 7 3 1 5]]

 [[5 9 3 5 1]
  [9 1 9 3 7]
  [6 8 7 4 1]
  [4 7 9 8 8]]]
--------------------


In [ ]:
"""
Each array has attributes ndim (the number of dimensions), shape (the size of each
dimension), and size (the total size of the array)
"""

print("Number of dimensions in x3:", x3.ndim)
print("Shape of x3:", x3.shape)
print("Size of x3:", x3.size)
print("dtype:", x3.dtype) # show the data type of x3 - useful attribute


"""
Other attributes include itemsize, which lists the size (in bytes) of each array 
element, and nbytes, which lists the total size (in bytes) of the array
"""

print("item size of x3:", x3.itemsize, "bytes")
print("nbytes of x3: ", x3.nbytes, "bytes") # In general, we expect that nbytes is equal to itemsize times size.

Number of dimensions in x3: 3
Shape of x3: (3, 4, 5)
Size of x3: 60
dtype: int64
item size of x3: 8 bytes
nbytes of x3:  480 bytes


### Array Indexing: Accessing Single Elements

If you are familiar with Python’s standard list indexing, indexing in NumPy will feel quite familiar. In a one-dimensional array, you can access the $i^{th}$ value (counting from zero) by specifying the desired index in square brackets, just as with Python lists

In [ ]:
x1 # array([6, 3, 7, 4, 6, 9])
x1[0] # 6 
x1[5] # 9
x1[0:3] # array([6, 3, 7])
x1[::2] # array([6, 7, 6]) - every

# To index from the end of the array, you can use negative indices
x1[-2] # 6 - the second last element
x1[-2:] # array([6, 9]) - the last two elements

array([6, 9])

In [56]:
"""
In a multidimensional array, you access items using a comma-separated tuple of
indices

x2 = array([[2, 6, 7, 4],
       [3, 7, 7, 2],
       [5, 4, 1, 7]])
"""

x2[0,0] # 2 - the first element of the first row
x2[2,0] # 5 - the first element of the third row

# You can also modify values using any of the above index notation

x2[0,1] = 42 # set the second element (6) of the first row to 42

x1[0] = 100.14159 # this will be truncated! -> array([100,   3,   7,   4,   6,   9])


### Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this :

> x[start:stop:step]

If any of these are unspecified, they default to the values start=0, stop=size of
dimension, step=1. We’ll take a look at accessing subarrays in one dimension and in
multiple dimensions.

#### One-dimensional subarrays

In [64]:
x = np.array(range(10))

x[0:5] # accesing the first five elements of x
x[5:10] # accessing the last five elements of x
x[::2] # accessing every other element of x

"""
A potentially confusing case is when the step value is negative. In this case, the
defaults for start and stop are swapped. This becomes a convenient way to reverse
an array
"""

x[::-1] # all elements, reversed

x[5::-2] # reversed every other from index 5

array([5, 3, 1])

#### Multidimensional subarrays

Multidimensional slices work in the same way, with multiple slices separated by commas

In [71]:
"""
x2 = array([[ 2, 42,  7,  4],
       [ 3,  7,  7,  2],
       [ 5,  4,  1,  7]])
"""

x2[:2, :3] # two rows, three columns
x2 [:2, ::2] # two rows, every other column

# subarray dimensions can even be reversed together
x2[::-1, ::-1] # reversed rows and columns

array([[ 7,  1,  4,  5],
       [ 2,  7,  7,  3],
       [ 4,  7, 42,  2]])

In [73]:
"""
Accessing array rows and columns. One commonly needed routine is accessing single
rows or columns of an array. You can do this by combining indexing and slicing,
using an empty slice marked by a single colon (:)

x2 = array([[ 2, 42,  7,  4],
       [ 3,  7,  7,  2],
       [ 5,  4,  1,  7]])
"""

x2[:,0] # first column of x2

array([2, 3, 5])

#### Subarrays as no-copy views & Creating copies of arrays


- Subarrays as no-copy views :

    One important—and extremely useful—thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.



In [ ]:
# subarrays as no-copy views
"""
x2 = array([[ 2, 42,  7,  4],
       [ 3,  7,  7,  2],
       [ 5,  4,  1,  7]])
"""

x2_sub = x2[:2,:2] # subarray of the first two rows and columns of x2

"""
Now if we modify this subarray, 
we’ll see that the original array is changed! Observe
"""

x2_sub [0,0] = 99 # this will change the first element of x2_sub to 99, and also change the first element of x2 to 99 
print("x2_sub:", x2_sub)
print("="*20)
print("x2:", x2[:2,:2]) 

"""
This default behavior is actually quite useful: it means that when we work with large
datasets, we can access and process pieces of these datasets without the need to copy
the underlying data buffer
"""

x2_sub: [[99 42]
 [ 3  7]]
x2: [[99 42]
 [ 3  7]]


* Creating copies of arrays

    Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the **copy()** method:

In [86]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99 42]
 [ 3  7]]


In [89]:
x2_sub_copy[0, 0] = 100
print(x2_sub_copy)
print("="*20)
print(x2[:2, :2]) # the original array is unchanged

[[100  42]
 [  3   7]]
[[99 42]
 [ 3  7]]


#### Reshaping of Arrays

Another useful type of operation is reshaping of arrays. The most flexible way of
doing this is with the **reshape()** method. For example, if you want to put the numbers 1 through 9 in a 3×3 grid

In [98]:
"""
Note that for this to work :
1. the size of the initial array must match the size of the reshaped array
2. the reshape method will use a no-copy view of the initial array
"""

grid = np.arange(1,10) # one-dimensional array of integers from 1 to 9
grid = grid.reshape((3,3)) # reshape it to a 3x3 array
print(grid)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [102]:
"""
Another common reshaping pattern is the conversion of a one-dimensional array
into a two-dimensional row or column matrix. You can do this with the reshape
method, or more easily by making use of the newaxis keyword within 
a slice operation
"""
x = np.array([1,2,3])
# row vector via reshape
x.reshape((1,3)) # this is a 1x3 array

# row vector via newaxis
x[np.newaxis, :] # this is the same as None, and can be used in indexing operations to add a new axis

array([[1, 2, 3]])

In [106]:
# column vector via reshape
x.reshape((3,1)) # this is a 3x1 array

# column vector via newaxis
x[:, np.newaxis] # this is the same as None, and can be used in


array([[1],
       [2],
       [3]])

### Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It’s also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays


#### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished
through the routines **np.concatenate, np.vstack, and np.hstack. np.concatenate**
takes a tuple or list of arrays as its first argument

In [112]:
x = np.array(range(3)) # output array([0, 1, 2])
y = np.array(range(3, 6)) # output array([3, 4, 5])

np.concatenate([x, y]) # concatenate the two arrays together

array([0, 1, 2, 3, 4, 5])

In [113]:
# You can also concatenate more than two arrays at once
z = [99, 99, 99]

np.concatenate([x, y, z])

array([ 0,  1,  2,  3,  4,  5, 99, 99, 99])

In [126]:
# np.concatenate can also be used for two-dimensional arrays

grid_1 = np.array(range(1,7)).reshape((2,3))
grid_2 = np.array(range(7,13)).reshape((2,3))

np.concatenate([grid_1, grid_2], axis=0) # concatenate along the first axis (the rows)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [127]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid_1, grid_2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
"""
For working with arrays of mixed dimensions, it can be clearer to use the 
np.vstack(vertical stack) and np.hstack (horizontal stack) functions
"""

x = np.array([90,91,92])
grid = np.array(range(7,13)).reshape((2,3))

# vertically stack the arrays
np.vstack([x, grid]) # stack arrays in sequence vertically (row wise)


array([[90, 91, 92],
       [ 7,  8,  9],
       [10, 11, 12]])

In [154]:
# horizontally stack the arrays
x_reshape = x[:2].reshape((2,1)) # reshape x to be a 2x1 array
np.hstack([x_reshape, grid_1]) # stack arrays in sequence horizontally (column wise


array([[90,  1,  2,  3],
       [91,  4,  5,  6]])

#### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions
**np.split, np.hsplit, and np.vsplit**. For each of these, we can pass a list of indices giving the split points

In [162]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) 
# [3,5] - the indices at which to split x. The first sub-array will be x[:3], 
# the second will be x[3:5], 
# and the third will be x[5:]
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [170]:
"""
Notice that N split points lead to N + 1 subarrays. The related functions np.hsplit
and np.vsplit are similar
"""

grid = np.array(range(16)).reshape((4,4))

# vertical split into four 1x4 arrays
upper,lower = np.vsplit(grid, 2) # split the array into two 2x4 subarrays

print("upper:\n", upper)
print("lower:\n", lower)

print (20*'-')

# horizontal split is similar, but splits along the second axis
left, right = np.hsplit(grid, 2) # split the array into two 2x4 subarrays
print("left:\n", left)
print("right:\n", right)

upper:
 [[0 1 2 3]
 [4 5 6 7]]
lower:
 [[ 8  9 10 11]
 [12 13 14 15]]
--------------------
left:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Computation on NumPy Arrays: Universal Functions

Computation on NumPy arrays can be very fast, or it can be very slow. The key to
making it fast is to use vectorized operations, generally implemented through NumPy’s universal functions (ufuncs). This section motivates the need for NumPy’s ufuncs, which can be used to **make repeated calculations on array elements much more efficient**. It then introduces many of the most common and useful arithmetic ufuncs available in the NumPy package.

#### Introducing UFuncs

For many types of operations, NumPy provides a convenient interface into just this
kind of statically typed, compiled routine. This is known as a vectorized operation. You can accomplish this by simply performing an operation on the array, which will then be applied to each element. This vectorized approach is designed to push the loop into the compiled layer that underlies NumPy, leading to much faster execution

Vectorized operations in NumPy are implemented via ufuncs, whose main purpose is
to quickly execute repeated operations on values in NumPy arrays. Ufuncs are
extremely flexible—before we saw an operation between a scalar and an array, but we
can also operate between two arrays

In [198]:
x = np.array(range(12,22))
y = np.arange(10)
y/x

array([0.        , 0.07692308, 0.14285714, 0.2       , 0.25      ,
       0.29411765, 0.33333333, 0.36842105, 0.4       , 0.42857143])

In [197]:
"""
And ufunc operations are not limited to one-dimensional arrays—they can act on
multidimensional arrays as well
"""
y = y.reshape(2, 5)
y*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

Computations using vectorization through ufuncs are nearly always more efficient
than their counterpart implemented through Python loops, especially as the arrays
grow in size. Any time you see such a loop in a Python script, you should consider
whether it can be replaced with a vectorized expression

### Exploring NumPy’s UFuncs

Ufuncs exist in two flavors: 
1. unary ufuncs, which operate on a single input
2. binary ufuncs, which operate on two inputs. 

We’ll see examples of both these types of functions here

#### Array arithmetic

NumPy’s ufuncs feel very natural to use because they make use of Python’s native
arithmetic operators. The standard addition, subtraction, multiplication, and division can all be used

In [200]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [201]:
"""
There is also a unary ufunc for negation, a ** operator for exponentiation, and a %
operator for modulus
"""
print("-x = ",-x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [204]:
"""
In addition, these can be strung together however you wish, and the standard order
of operations is respected
"""
x = np.arange(4)
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [205]:
"""
All of these arithmetic operations are simply convenient wrappers around specific
functions built into NumPy; for example, the + operator is a wrapper for the add
function
"""

np.add(x, 2)

array([2, 3, 4, 5])

![numpy-operator](../images/unfuncs-operator.png)

#### Absolute value

ust as NumPy understands Python’s built-in arithmetic operators, it also understands Python’s built-in absolute value function

In [ ]:
x = np.array([-2,-1, 0, 1, 2])

# absoilute value with python built-in abs() function
abs(x)

# The corresponding NumPy ufunc is np.absolute, which is also available under the alias np.abs
# absolute value with numpy ufunc
np.absolute(x) # works the same as abs(x)
np.abs(x) # also works the same as abs(x)

array([2, 1, 0, 1, 2])

#### Trigonometric functions

NumPy provides a large number of useful ufuncs, and some of the most useful for the
data scientist are the trigonometric functions

In [213]:
# let's initiate an array
theta = np.linspace(0, np.pi, 3) # array([0.        , 1.57079633, 3.14159265])

# compute some trigonometric functions
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


The values are computed to within machine precision, which is why values that
should be zero do not always hit exactly zero. Inverse trigonometric functions are also available

In [216]:
x = np.array(np.linspace(-1,1,3))

# compute the inverse trigonometric functions
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1.  0.  1.]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


#### Exponents and logarithms

Another common type of operation available in a NumPy ufunc are the exponentials

In [219]:
x = [1,2,3]

# compute the exponentials of these values
print("x = ", x)
print("exp^x = ", np.exp(x))
print("2^x = ", np.exp2(x))
print("3^x =", np.power(3,x))

x =  [1, 2, 3]
exp^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x = [ 3  9 27]


In [220]:
"""
The inverse of the exponentials, the logarithms, are also available. The basic np.log
gives the natural logarithm; if you prefer to compute the base-2 logarithm or the
base-10 logarithm, these are available as well
"""

print("x = ", x)
print("natural log of x = ", np.log(x))
print("base-2 log of x = ", np.log2(x))
print("base-10 log of x = ", np.log10(x))

x =  [1, 2, 3]
natural log of x =  [0.         0.69314718 1.09861229]
base-2 log of x =  [0.        1.        1.5849625]
base-10 log of x =  [0.         0.30103    0.47712125]


In [221]:
"""
There are also some specialized versions that are useful for maintaining precision
with very small input
"""

x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


#### Specialized ufuncs

NumPy has many more ufuncs available, including hyperbolic trig functions, bitwise
arithmetic, comparison operators, conversions from radians to degrees, rounding and
remainders, and much more. A look through the NumPy documentation reveals a lot
of interesting functionality.

Another excellent source for more specialized and obscure ufuncs is the submodule
scipy.special. If you want to compute some obscure mathematical function on
your data, chances are it is implemented in scipy.special

In [222]:
from scipy import special

# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2) =", special.beta(x, 2))

gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2) = [0.5        0.03333333 0.00909091]


In [223]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x) =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x) = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


There are many, many more ufuncs available in both NumPy and scipy.special.
Because the documentation of these packages is available online, a web search along
the lines of “gamma function python” will generally find the relevant information

### Advanced Ufunc Features

#### Specifying output

For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored. Rather than creating a temporary array, you can use this to write computation results directly to the memory location where you’d like them to be. For all ufuncs, you can do this using the out argument of the function

In [227]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


This can even be used with array views. For example, we can write the results of a
computation to every other element of a specified array

In [231]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


If we had instead written y[::2] = 2 ** x, this would have resulted in the creation of a temporary array to hold the results of 2 ** x, followed by a second operation copying those values into the y array. This doesn’t make much of a difference for such a small computation, but for very large arrays the memory savings from careful use of the out argument can be significant


#### Aggregates

For binary ufuncs, there are some interesting aggregates that can be computed
directly from the object. For example, if we’d like to reduce an array with a particular operation, we can use the **reduce method of any ufunc**. A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

In [238]:
"""
calling reduce on the add ufunc returns the sum of all elements in the array
"""
x = np.arange(1,6) # array([1, 2, 3, 4, 5])
np.add.reduce(x)

np.int64(15)

In [239]:
"""
calling reduce on the multiply ufunc results in the product of all array elements
"""
np.multiply.reduce(x)

np.int64(120)

In [244]:
"""
If we’d like to store all the intermediate results of the computation, 
we can instead use accumulate
"""
# initial x array is array([1, 2, 3, 4, 5])
np.add.accumulate(x) # result : array([ 1,  3,  6, 10, 15])
np.multiply.accumulate(x) # result : array([  1,   2,   6,  24, 120])

array([  1,   2,   6,  24, 120])

#### Outer products

any ufunc can compute the output of all pairs of two different inputs using
the outer method. This allows you, in one line, to do things like create a multiplication table

In [247]:
x = np.arange(1, 6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

### Aggregations: Min, Max, and Everything in Between

Often when you are faced with a large amount of data, a first step is to compute summary statistics for the data in question. Perhaps the most common summary statistics are the mean and standard deviation, which allow you to summarize the “typical” values in a dataset, but other aggregates are useful as well (the sum, product, median, minimum and maximum, quantiles, etc.)

NumPy has fast built-in aggregation functions for working on arrays; we’ll discuss
and demonstrate some of them here.

#### Summing the Values in an Array


In [ ]:
# initiate x random integer
L = np.random.random(100)
np.sum(L) # aggregate sum of all elements in L with numpy func
sum(L) # aggregate sum of all elements in L with python built-in func

# the main difference between the two is that np.sum is optimized for performance 
# and can be much faster than the built-in sum function, 
# especially for large arrays. A
# dditionally, np.sum can handle multi-dimensional arrays and has more options 
# for controlling the behavior of the summation (e.g., specifying the axis along which to sum).

np.float64(48.97041323438124)

#### Minimum and Maximum

Similarly, Python has built-in min and max functions, used to find the minimum value and maximum value of any given array

In [271]:
big_array = np.random.rand(1000000)

# min, max through built-in functions
min(big_array), max(big_array)

# min, max through numpy functions - much faster!
np.min(big_array), np.max(big_array)

# alternatively, we can use the methods of the array itself
big_array.min(), big_array.max()

(np.float64(4.970905526091585e-07), np.float64(0.9999987182464998))

#### Multidimensional aggregates

One common type of aggregation operation is an aggregate along a row or column.
Say you have some data stored in a two-dimensional array

In [ ]:
np.random.seed(42) # Set the random seed to 42 for reproducibility
M = np.random.rand(3,4)

# each NumPy aggregation function will return the aggregate over the entire array
"""
array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])
"""

M.sum() # output : np.float64(6.191861705984546)

"""
Aggregation functions take an additional argument specifying the axis along which
the aggregate is computed. For example, we can find the minimum value within each
column by specifying axis=0 
Note : 
- axis=0 in short is row direction, - the first axis, which is the vertical direction (down the rows)
- axis=1 in short is column direction, - the second axis, which is the horizontal direction (across the columns
"""

M.min(axis=0) # output : array([0.15601864, 0.15599452, 0.02058449, 0.59865848])
M.min(axis=1) # output : array([0.37454012, 0.05808361, 0.02058449])

array([0.15601864, 0.15599452, 0.02058449, 0.59865848])

#### Other aggregation functions

NumPy provides many other aggregation functions, but we won’t discuss them in
detail here. Additionally, most aggregates have a NaN-safe counterpart that computes the result while ignoring missing values, which are marked by the special IEEE floating-point NaN value. Some of these NaN-safe functions were not added until NumPy 1.8, so they will not be available in older NumPy versions.

![aggregates-function](../images/aggregates-func.png)

## Computation on Arrays: Broadcasting

We saw in the previous section how NumPy’s universal functions can be used to vectorize operations and thereby remove slow Python loops. Another means of vectorizing operations is to use NumPy’s broadcasting functionality. 

> Broadcasting is simply a set of rules for applying binary ufuncs (addition, subtraction, multiplication, etc.) on arrays of different sizes

### Introducing Broadcasting

Recall that for arrays of the same size, binary operations are performed on an
element-by-element basis

In [ ]:
import numpy as np

a = np.array([0, 1, 2])
b = np.array([5, 5, 5])

a+b # output : array([5, 6, 7])

"""
Broadcasting allows these types of binary operations to be performed 
on arrays of different sizes for example, we can just as easily add 
a scalar (think of it as a zero dimensional array) to an array
"""

a+5 # output : array([5, 6, 7]) = array([0, 1, 2]) + array([5,5,5]) 

array([5, 6, 7])

In [303]:
"""
We can similarly extend this to arrays of higher dimension. 
Observe the result when we add a one-dimensional array to a two-dimensional array

M = array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

a = array([0, 1, 2])
"""

M = np.ones((3,3))
M + a
"""
output : array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

While these examples are relatively easy to understand, more complicated cases can
involve broadcasting of both arrays. Consider the following example
"""
a = np.arange(3)
b = np.arange(3)[:, np.newaxis] 

print ("a = ", a)
print("="*20)
print ("b = ", b)

a =  [0 1 2]
b =  [[0]
 [1]
 [2]]


In [304]:
# computing the sum of a and b will result in a 3x3 array (on broadcasting rules)

a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Just as before we stretched or broadcasted one value to match the shape of the other, here we’ve stretched both a and b to match a common shape, and the result is a two dimensional array! The geometry of these examples is visualized

![broadcasting-ilustration](../images/broadcasting-illustration.png)

The light boxes represent the broadcasted values: again, this extra memory is not
actually allocated in the course of the operation, but it can be useful conceptually to imagine that it is.

### Rules of Broadcasting

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:
* Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

* Rule 2: If the shape of the two arrays does not match in any dimension, the array
with shape equal to 1 in that dimension is stretched to match the other shape.

* Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

## Comparisons, Masks, and Boolean Logic

This section covers the use of Boolean masks to examine and manipulate values
within NumPy arrays. Masking comes up when you want to extract, modify, count, or
otherwise manipulate values in an array based on some criterion: for example, you
might wish to count all values greater than a certain value, or perhaps remove all outliers that are above some threshold. In NumPy, Boolean masking is often the most efficient way to accomplish these types of tasks