## Fixed-Type Arrays in Python

Python offers several different options for storing data in efficient, fixed-type data buffers. The built-in array module (available since Python 3.3) can be used to create dense arrays of a uniform type:

In [ ]:
import numpy as np
import array as arr

L = np.array(range(1, 10))

A = arr.array('i', L) # Here 'i' is a type code indicating the contents are integers.
print (A)

# NumPy arrays can explicitly be multidimensional; here’s one way of initializing a multidimensional array
# nested lists result in multidimensional arrays
np.array([range(i,i+3) for i in (2,4,6)])



array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy. Here are several examples:

In [9]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)


array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [13]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)

np.arange(0, 20, 2)

# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))


array([[0.8618796 , 0.69079353, 0.57480433],
       [0.46290401, 0.8256618 , 0.55494367],
       [0.69157264, 0.4111524 , 0.32543866]])

In [19]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1

np.random.normal(0,1,(3,3))

array([[-1.46604827,  0.79907927,  0.46915602],
       [-0.7102526 , -1.16602262, -0.81090017],
       [-0.37697882,  1.81241394,  0.66540366]])

In [22]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0,10,(3,3))

array([[5, 6, 1],
       [2, 4, 1],
       [8, 8, 3]])

In [25]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
# before using this array, you should always fill it with your own values, either with array indexing or with the fill() method

np.empty(3)

array([1., 1., 1.])

## NumPy Standard Data Types

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations. Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

<img src="../images/numpy%20data%20type.png" width="600" alt="numpy data type">


## The Basics of NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation:
even newer tools like Pandas are built around the NumPy array. This sec‐tion will present several examples using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays. While the types of operations shown here may seem a bit dry and pedantic

We’ll cover a few categories of basic array manipulations here:

- Attributes of arrays
Determining the size, shape, memory consumption, and data types of arrays

- Indexing of arrays
Getting and setting the value of individual array elements

- Slicing of arrays
Getting and setting smaller subarrays within a larger array

- Reshaping of arrays
Changing the shape of a given array

- Joining and splitting of arrays
Combining multiple arrays into one, and splitting one array into many

### NumPy Array Attributes

First let’s discuss some useful array attributes. We’ll start by defining three random arrays: a one-dimensional, two-dimensional, and three-dimensional array. We’ll use NumPy’s random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run


In [35]:
np.random.seed(42) # Set the random seed to 42 for reproducibility

x1 = np.random.randint(10, size=6) # One-dimensional array of 6 random integers in the range 0-9
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array of shape (3, 4, 5) with random integers in the range 0-9

print(x1)
print(20*'-')

print(x2)
print(20*'-')

print(x3)
print(20*'-')

[6 3 7 4 6 9]
--------------------
[[2 6 7 4]
 [3 7 7 2]
 [5 4 1 7]]
--------------------
[[[5 1 4 0 9]
  [5 8 0 9 2]
  [6 3 8 2 4]
  [2 6 4 8 6]]

 [[1 3 8 1 9]
  [8 9 4 1 3]
  [6 7 2 0 3]
  [1 7 3 1 5]]

 [[5 9 3 5 1]
  [9 1 9 3 7]
  [6 8 7 4 1]
  [4 7 9 8 8]]]
--------------------


In [ ]:
"""
Each array has attributes ndim (the number of dimensions), shape (the size of each
dimension), and size (the total size of the array)
"""

print("Number of dimensions in x3:", x3.ndim)
print("Shape of x3:", x3.shape)
print("Size of x3:", x3.size)
print("dtype:", x3.dtype) # show the data type of x3 - useful attribute


"""
Other attributes include itemsize, which lists the size (in bytes) of each array 
element, and nbytes, which lists the total size (in bytes) of the array
"""

print("item size of x3:", x3.itemsize, "bytes")
print("nbytes of x3: ", x3.nbytes, "bytes") # In general, we expect that nbytes is equal to itemsize times size.

Number of dimensions in x3: 3
Shape of x3: (3, 4, 5)
Size of x3: 60
dtype: int64
item size of x3: 8 bytes
nbytes of x3:  480 bytes


### Array Indexing: Accessing Single Elements

If you are familiar with Python’s standard list indexing, indexing in NumPy will feel quite familiar. In a one-dimensional array, you can access the $i^{th}$ value (counting from zero) by specifying the desired index in square brackets, just as with Python lists

In [ ]:
x1 # array([6, 3, 7, 4, 6, 9])
x1[0] # 6 
x1[5] # 9
x1[0:3] # array([6, 3, 7])
x1[::2] # array([6, 7, 6]) - every

# To index from the end of the array, you can use negative indices
x1[-2] # 6 - the second last element
x1[-2:] # array([6, 9]) - the last two elements

array([6, 9])

In [56]:
"""
In a multidimensional array, you access items using a comma-separated tuple of
indices

x2 = array([[2, 6, 7, 4],
       [3, 7, 7, 2],
       [5, 4, 1, 7]])
"""

x2[0,0] # 2 - the first element of the first row
x2[2,0] # 5 - the first element of the third row

# You can also modify values using any of the above index notation

x2[0,1] = 42 # set the second element (6) of the first row to 42

x1[0] = 100.14159 # this will be truncated! -> array([100,   3,   7,   4,   6,   9])


### Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this :

> x[start:stop:step]

If any of these are unspecified, they default to the values start=0, stop=size of
dimension, step=1. We’ll take a look at accessing subarrays in one dimension and in
multiple dimensions.

#### One-dimensional subarrays

In [64]:
x = np.array(range(10))

x[0:5] # accesing the first five elements of x
x[5:10] # accessing the last five elements of x
x[::2] # accessing every other element of x

"""
A potentially confusing case is when the step value is negative. In this case, the
defaults for start and stop are swapped. This becomes a convenient way to reverse
an array
"""

x[::-1] # all elements, reversed

x[5::-2] # reversed every other from index 5

array([5, 3, 1])

#### Multidimensional subarrays

Multidimensional slices work in the same way, with multiple slices separated by commas

In [71]:
"""
x2 = array([[ 2, 42,  7,  4],
       [ 3,  7,  7,  2],
       [ 5,  4,  1,  7]])
"""

x2[:2, :3] # two rows, three columns
x2 [:2, ::2] # two rows, every other column

# subarray dimensions can even be reversed together
x2[::-1, ::-1] # reversed rows and columns

array([[ 7,  1,  4,  5],
       [ 2,  7,  7,  3],
       [ 4,  7, 42,  2]])

In [73]:
"""
Accessing array rows and columns. One commonly needed routine is accessing single
rows or columns of an array. You can do this by combining indexing and slicing,
using an empty slice marked by a single colon (:)

x2 = array([[ 2, 42,  7,  4],
       [ 3,  7,  7,  2],
       [ 5,  4,  1,  7]])
"""

x2[:,0] # first column of x2

array([2, 3, 5])

#### Subarrays as no-copy views & Creating copies of arrays


- Subarrays as no-copy views :

    One important—and extremely useful—thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.



In [ ]:
# subarrays as no-copy views
"""
x2 = array([[ 2, 42,  7,  4],
       [ 3,  7,  7,  2],
       [ 5,  4,  1,  7]])
"""

x2_sub = x2[:2,:2] # subarray of the first two rows and columns of x2

"""
Now if we modify this subarray, 
we’ll see that the original array is changed! Observe
"""

x2_sub [0,0] = 99 # this will change the first element of x2_sub to 99, and also change the first element of x2 to 99 
print("x2_sub:", x2_sub)
print("="*20)
print("x2:", x2[:2,:2]) 

"""
This default behavior is actually quite useful: it means that when we work with large
datasets, we can access and process pieces of these datasets without the need to copy
the underlying data buffer
"""

x2_sub: [[99 42]
 [ 3  7]]
x2: [[99 42]
 [ 3  7]]


* Creating copies of arrays

    Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the **copy()** method:

In [86]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99 42]
 [ 3  7]]


In [89]:
x2_sub_copy[0, 0] = 100
print(x2_sub_copy)
print("="*20)
print(x2[:2, :2]) # the original array is unchanged

[[100  42]
 [  3   7]]
[[99 42]
 [ 3  7]]


#### Reshaping of Arrays

Another useful type of operation is reshaping of arrays. The most flexible way of
doing this is with the **reshape()** method. For example, if you want to put the numbers 1 through 9 in a 3×3 grid

In [98]:
"""
Note that for this to work :
1. the size of the initial array must match the size of the reshaped array
2. the reshape method will use a no-copy view of the initial array
"""

grid = np.arange(1,10) # one-dimensional array of integers from 1 to 9
grid = grid.reshape((3,3)) # reshape it to a 3x3 array
print(grid)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [102]:
"""
Another common reshaping pattern is the conversion of a one-dimensional array
into a two-dimensional row or column matrix. You can do this with the reshape
method, or more easily by making use of the newaxis keyword within 
a slice operation
"""
x = np.array([1,2,3])
# row vector via reshape
x.reshape((1,3)) # this is a 1x3 array

# row vector via newaxis
x[np.newaxis, :] # this is the same as None, and can be used in indexing operations to add a new axis

array([[1, 2, 3]])

In [106]:
# column vector via reshape
x.reshape((3,1)) # this is a 3x1 array

# column vector via newaxis
x[:, np.newaxis] # this is the same as None, and can be used in


array([[1],
       [2],
       [3]])

### Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It’s also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays


#### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished
through the routines **np.concatenate, np.vstack, and np.hstack. np.concatenate**
takes a tuple or list of arrays as its first argument

In [112]:
x = np.array(range(3)) # output array([0, 1, 2])
y = np.array(range(3, 6)) # output array([3, 4, 5])

np.concatenate([x, y]) # concatenate the two arrays together

array([0, 1, 2, 3, 4, 5])

In [113]:
# You can also concatenate more than two arrays at once
z = [99, 99, 99]

np.concatenate([x, y, z])

array([ 0,  1,  2,  3,  4,  5, 99, 99, 99])

In [126]:
# np.concatenate can also be used for two-dimensional arrays

grid_1 = np.array(range(1,7)).reshape((2,3))
grid_2 = np.array(range(7,13)).reshape((2,3))

np.concatenate([grid_1, grid_2], axis=0) # concatenate along the first axis (the rows)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [127]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid_1, grid_2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
"""
For working with arrays of mixed dimensions, it can be clearer to use the 
np.vstack(vertical stack) and np.hstack (horizontal stack) functions
"""

x = np.array([90,91,92])
grid = np.array(range(7,13)).reshape((2,3))

# vertically stack the arrays
np.vstack([x, grid]) # stack arrays in sequence vertically (row wise)


array([[90, 91, 92],
       [ 7,  8,  9],
       [10, 11, 12]])

In [154]:
# horizontally stack the arrays
x_reshape = x[:2].reshape((2,1)) # reshape x to be a 2x1 array
np.hstack([x_reshape, grid_1]) # stack arrays in sequence horizontally (column wise


array([[90,  1,  2,  3],
       [91,  4,  5,  6]])

#### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions
**np.split, np.hsplit, and np.vsplit**. For each of these, we can pass a list of indices giving the split points

In [162]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) 
# [3,5] - the indices at which to split x. The first sub-array will be x[:3], 
# the second will be x[3:5], 
# and the third will be x[5:]
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [170]:
"""
Notice that N split points lead to N + 1 subarrays. The related functions np.hsplit
and np.vsplit are similar
"""

grid = np.array(range(16)).reshape((4,4))

# vertical split into four 1x4 arrays
upper,lower = np.vsplit(grid, 2) # split the array into two 2x4 subarrays

print("upper:\n", upper)
print("lower:\n", lower)

print (20*'-')

# horizontal split is similar, but splits along the second axis
left, right = np.hsplit(grid, 2) # split the array into two 2x4 subarrays
print("left:\n", left)
print("right:\n", right)

upper:
 [[0 1 2 3]
 [4 5 6 7]]
lower:
 [[ 8  9 10 11]
 [12 13 14 15]]
--------------------
left:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Computation on NumPy Arrays: Universal Functions